### ISSUE TITLE
Query params include leads to error

### ISSUE THREAD

**Issue by al3x-edge** [vt-elixir/ja_resource#67]
Currently getting an error while trying to include a relation on a controller.  I believe I have everything setup and preload but hard to find documentation which isn't pieced around.

Controller Opts:
```Elixir
  def handle_index_query(%{query_params: qp}, query) do
    query
    |> InqAPI.Repo.paginate(qp)
  end
  def handle_index(conn, %{"include" => include}) do
    includes = String.split(include, ",")
    query = records(conn)
    query = if "asset" in includes, do: Ecto.Query.preload(query, [:asset]), else: query
    query
  end

...

  def serialization_opts(_conn, %{"fields" => f, "include" => i}, %Scrivener.Page{} = models) do
    [
      meta: %{
        current_page: models.page_number, page_size: models.page_size,
        total_pages: models.total_pages, total_records: models.total_entries
      },
      include: i, fields: f
    ]
  end
  def serialization_opts(_conn, %{"include" => i}, %Scrivener.Page{} = models) do
    [
      meta: %{
        current_page: models.page_number, page_size: models.page_size,
        total_pages: models.total_pages, total_records: models.total_entries
      },
      include: i,
    ]
  end
  def serialization_opts(_conn, %{"fields" => f}, %Scrivener.Page{} = models) do
    [
      meta: %{
        current_page: models.page_number, page_size: models.page_size,
        total_pages: models.total_pages, total_records: models.total_entries
      },
      fields: f
    ]
  end
  def serialization_opts(_conn, _params, %Scrivener.Page{} = models) do
    [
      meta: %{
        current_page: models.page_number, page_size: models.page_size,
        total_pages: models.total_pages, total_records: models.total_entries
      }
    ]
  end
```

```
server_1    | Request: GET /api/favorites?sort=-inserted_at&include=asset
server_1    | ** (exit) an exception was raised:
server_1    |     ** (UndefinedFunctionError) function nil.id/2 is undefined or private
server_1    |         nil.id(2, %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{data: %Scrivener.Page{entries: [%InqAPI.Favorite{__meta__: #Ecto.Schema.Metadata<:loaded, "favorites">, asset: %InqAPI.Asset{__meta__: #Ecto.Schema.Metadata<:loaded, "assets">, amazon_file_locations: [], classifications: #Ecto.Association.NotLoaded<association :classifications is not loaded>, description: "Star map of Earth -- how did this get here?", favorites: #Ecto.Association.NotLoaded<association :favorites is not loaded>, file_locations: nil, file_type: "Image", filename: "DSC0012343.jpg", id: 2, inserted_at: ~N[2017-08-22 19:13:28.649367], library: #Ecto.Association.NotLoaded<association :library is not loaded>, library_id: 1, metadata: nil, name: "Starmap - Earth", organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, organization_id: 1, owner: #Ecto.Association.NotLoaded<association :owner is not loaded>, owner_id: 1, ratings: #Ecto.Association.NotLoaded<association :ratings is not loaded>, tags: "star-map", updated_at: ~N[2017-08-22 19:13:28.668679], user_libraries: #Ecto.Association.NotLoaded<association :user_libraries is not loaded>}, asset_id: 2, id: 2, inserted_at: ~N[2017-08-22 19:13:28.770694], organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, organization_id: 1, updated_at: ~N[2017-08-22 19:13:28.770703], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 1}, %InqAPI.Favorite{__meta__: #Ecto.Schema.Metadata<:loaded, "favorites">, asset: %InqAPI.Asset{__meta__: #Ecto.Schema.Metadata<:loaded, "assets">, amazon_file_locations: [], classifications: #Ecto.Association.NotLoaded<association :classifications is not loaded>, description: "Star map of Kashyyyk", favorites: #Ecto.Association.NotLoaded<association :favorites is not loaded>, file_locations: nil, file_type: "Image", filename: "DSC0012342.jpg", id: 1, inserted_at: ~N[2017-08-22 19:13:28.620460], library: #Ecto.Association.NotLoaded<association :library is not loaded>, library_id: 1, metadata: nil, name: "Starmap - Kashyyyk", organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, organization_id: 1, owner: #Ecto.Association.NotLoaded<association :owner is not loaded>, owner_id: 1, ratings: #Ecto.Association.NotLoaded<association :ratings is not loaded>, tags: "star-map", updated_at: ~N[2017-08-22 19:13:28.661090], user_libraries: #Ecto.Association.NotLoaded<association :user_libraries is not loaded>}, asset_id: 1, id: 1, inserted_at: ~N[2017-08-22 19:13:28.761431], organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, organization_id: 1, updated_at: ~N[2017-08-22 19:13:28.761438], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 1}], page_number: 1, page_size: 20, total_entries: 2, total_pages: 1}, layout: false, opts: [meta: %{current_page: 1, page_size: 20, total_pages: 1, total_records: 2}, include: "asset"], org: %InqAPI.Organization{__meta__: #Ecto.Schema.Metadata<:loaded, "organizations">, audit_logs: #Ecto.Association.NotLoaded<association :audit_logs is not loaded>, deactivated_datetime: nil, groups: #Ecto.Association.NotLoaded<association :groups is not loaded>, id: 1, inserted_at: ~N[2017-08-22 19:13:27.121655], is_active: true, libraries: #Ecto.Association.NotLoaded<association :libraries is not loaded>, security_roles: #Ecto.Association.NotLoaded<association :security_roles is not loaded>, settings: %{}, subdomain: "jedis", updated_at: ~N[2017-08-22 19:13:27.121663], user_libraries: #Ecto.Association.NotLoaded<association :user_libraries is not loaded>, users: #Ecto.Association.NotLoaded<association :users is not loaded>}, org_id: 1}, before_send: [#Function<1.111529033/1 in Plug.Logger.call/2>], body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.969.0>, params: %{"include" => "asset", "sort" => "-inserted_at"}, path_info: ["api", "favorites"], path_params: %{}, peer: {{172, 24, 0, 1}, 55312}, port: 4000, private: %{InqAPI.Router => {[], %{}}, :guardian_default_claims => {:ok, %{}}, :guardian_default_jwt => "", :guardian_default_resource => %InqAPI.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, assets: #Ecto.Association.NotLoaded<association :assets is not loaded>, avatar_location: "https://placehold.it/350x150", email_address: "luke@jedis.org", favorites: #Ecto.Association.NotLoaded<association :favorites is not loaded>, first_name: "Luke", groups: #Ecto.Association.NotLoaded<association :groups is not loaded>, id: 1, inserted_at: ~N[2017-08-22 19:13:27.901438], is_active: true, is_realm_admin: true, job_title: "Master Jedi", last_login: #Ecto.Date<2017-08-22>, last_name: "Skywalker", organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, organization_id: 1, password: nil, password_change_required: false, password_digest: "", phone_number: "555.555.5555", ratings: #Ecto.Association.NotLoaded<association :ratings is not loaded>, security_roles: #Ecto.Association.NotLoaded<association :security_roles is not loaded>, updated_at: ~N[2017-08-22 19:13:27.901448]}, :phoenix_action => :index, :phoenix_controller => InqAPI.FavoriteController, :phoenix_endpoint => InqAPI.Endpoint, :phoenix_format => "json-api", :phoenix_layout => {InqAPI.LayoutView, :app}, :phoenix_pipelines => [:jsonapi], :phoenix_router => InqAPI.Router, :phoenix_template => "index.json-api", :phoenix_view => InqAPI.FavoriteView, :plug_session_fetch => #Function<1.131660147/1 in Plug.Session.fetch_session/1>}, query_params: %{"include" => "asset", "sort" => "-inserted_at"}, query_string: "sort=-inserted_at&include=asset", remote_ip: {172, 24, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4000"}, {"user-agent", "insomnia/5.7.14"}, {"accept-encoding", "deflate, gzip"}, {"cookie", "__profilin=p%3Dt"}, {"content-type", "application/json"}, {"accept", "application/vnd.api+json"}, {"x-subdomain-slug", "jedis"}, {"authorization", "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE1MDQxOTkyMTIsImlhdCI6MTUwNDE5NTYxMiwiaXNzIjoiSW5xQVBJIiwianRpIjoiNzBiODE0ZWMtODc3MS00MDc3LWFhMWUtZDhjYTY2YTJiM2UxIiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.IqVfA9xV0QoQ1YSgLLtue3qHCg2FqFteIafu3AxeI-k2le8zUEMSzM8R2QKgQMfrfNHZ1qS1vg5dI7uHPjKehQ"}, {"content-length", "0"}], request_path: "/api/favorites", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "e06s3k7r8jt3qvt4rv7qicrculpe3nfv"}], scheme: :http, script_name: [], secret_key_base: "bMPXafGOvQuLnGLxPZ+TX8QhA1h3VMmSkE0HCCAFvlNmKnz0oq4KjZcRHpuw/kvN", state: :unset, status: nil})
server_1    |         (ja_serializer) lib/ja_serializer/builder/resource_object.ex:20: JaSerializer.Builder.ResourceObject.build/1
server_1    |         (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
server_1    |         (ja_serializer) lib/ja_serializer/builder/included.ex:40: JaSerializer.Builder.Included.resource_objects_for/4
server_1    |         (ja_serializer) lib/ja_serializer/builder/included.ex:67: JaSerializer.Builder.Included.resources_for_relationship/4
server_1    |         (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2 (truncated)
```

**Comment by max-konin** [comment]
@al3x-edge Did you resolve this issue. I have some error
